MORNING = [
    "good morning rigel!!",
    "hiya riiigel. ݁₊ ⊹ . ݁",
    "hai Bigel",
    "top o' the morning R",
    "helo ₍ᐢ. .ᐢ₎",
    "GIRL HYDRATE FIRST,"
    "おはよう ( ˶ˆᗜˆ˵ )",
    "gute morgen r-ballz",
    "here we go again",
    "girl what if i still wanted to sleep",

    "morning starfriend",
    "rise n shine (optional)",
    "gm tiny universe",
    "gm rigel ⋆｡°✩",
    "hello sunshine??",
    "good morning little light",
    "wake up bestie",
    "morning… gently",
    "good morning. breathe.",
    "a new day… suspicious",
    "ok we're awake now",
    "i made u a morning",
    "morning rigel ༘⋆",

    "gm i guess",
    "wake up!! (derogatory)",
    "good morning creature",
    "morning gremlin mode",
    "morning… why",
    "gm. i regret it already",
    "time to do capitalism",
    "u up? unfortunately",
    "gm pls dont perceive me",
    "wake up riceball",
    "rise and exist",
    "morning. no thoughts.",
    "lets pretend we're fine",
    "good morning (menacing)",

    "gm rigel my beloved",
    "hi baby star",
    "morning, lil orb",
    "good morning sweet riceball",
    "gm bestie ✩",
    "hiya cutie rigel !!!!!!!!! WAHHH",
    "hi hi hi hi",
    "good morning u icon",
    "gm rigel u legend",
    "morning!! i missed u",

    "morning. again.",
    "it is morning. sadly.",
    "gm. loading…",
    "booting up…",
    "system online… maybe",
    "hello. we begin.",
    "morning update: alive",
    "status: awake-ish",
    "morning check: vibes?",
    "gm. pls send coffee !!!!!!",

    # extra: multilingual-ish
    "hola rigel :>",
    "ohayo rigel!!",
    "guten morgen rigel",
    "bonjour… again",
    "salut petit star",

    "gm ₍ᐢ. .ᐢ₎",
    "morning (ᗜˬᗜ)",
    "gm ( ˶ˆᗜˆ˵ )",
    "gm ⋆★☆",
    "morning ♡",
    "hiya ⋆｡°✩",
    "gm (ᵕ)",
    "helooo ᵕᵕ",
    "wake up ⋆",
    
    "morning sweet riceball",
    "gm rigel ⋆ stay gentle",
    "hi rigel. new day.",
    "morning hugs (optional)",
    "gm. u made it. !!!! wah",
    "good morning, tiny cosmos",
    "morning!! proud of u",
    "gm rigel, breathe ok",
    "hello lil orbit",
    "gm stardust friend",
    "DID UPEED IN DA BED",

    # sleepy + relatable
    "gm... eyes still closed",
    "morning. i refuse.",
    "good morning... allegedly",
    "gm rigel. 5 more mins",
    "hi. i'm still loading.",
    "gm. body awake, soul not",
    "morning... can we not",
    "wake up… gently",
    "gm. u up? tragic",
    "its morning again??",
    "good morning. sip water.",
    "morning rigel. no thoughts",

    "gm rigel!! beep beep. BLEEP!!!!",
    "rise n whine",
    "morning gremlin reporting",
    "GLORY OF THE SNOOOREEE",
    "wake up bestie (pls)",
    "gm. lets cause problems",
    "good morning menace",
    "morning rigel. chaos time",
    "hello u beautiful disaster",
    "gm rigel. do crimes? (no)",
    "wake up and be weird",
    "morning rigel. slay??",
    "gm. world loading...",

    "gm rigel. *curtain rises*",
    "good morning, main character",
    "morning... the plot begins",
    "gm rigel. act 1",
    "wake up. the saga continues",
    "gm. another chapter...",
    "good morning. we commence.",
    "morning rigel. new episode",
    "good morning. roll credits?",

    "gm rigel drink water",
    "good morning!! eat smth pls",
    "gm. stretch ur lil bones",
    "morning rigel. snacks soon?",
    "gm bestie. take ur meds?",
    "good morning. be kind 2 u",
    "gm rigel. slow start ok",
    "hello. hydrate challenge",
    "gm. breakfast? perhaps."
    
    
    
]


AFTERNOON = [
    "hey hey rigel",
    "afternoon chaos engaged",
    "hello !!!! HELLLOO",
    "hi. still alive.",
    "helo! did u have a snack yet 2day??",

    "hi rigel!!",
    "afternoon rigel :)",
    "hey sunshine",
    "hello hello!",
    "how's it goin",
    "midday check-in",
    "hi bestie",
    "ok hi we're back",
    "hi hi hi",
    "hey u",

    "drink water rn",
    "snack break??",
    "u ate today right",
    "pls hydrate",
    "tiny snack time",
    "go stretch ur legs",
    "blink. unclench jaw.",
    "drink water i beg",
    "have u had fruit??",
    "pls eat something small (my [fill in the blank])",

    "afternoon… suspicious",
    "we're in the thick of it",
    "midday grind (ugh)",
    "the sun is loud",
    "why is it so bright",
    "still alive? ok cool",
    "afternoon status: chaotic",
    "hi. i am processing.",
    "hello?? HELLO???",
    "hello i have returned",
    "afternoon goblin mode",
    "ok time for nonsense",
    "vibes check: mid",

    "afternoon. we persist.",
    "we continue… somehow",
    "time is moving again",
    "midday: still here",
    "halfway thru the day",
    "the day is happening",
    "existence update: ongoing",
    "we're doing our best",

    "hi rigel my star",
    "hey hey cutie",
    "hi love ✩",
    "hi stardust",
    "hey riceball ♡",
    "hi hi pretty light",
    "hey big rigel energy",
    "hello my sweet orb",

    "afternoon ₍ᐢ. .ᐢ₎",
    "hey (ᗜˬᗜ)",
    "hiya ( ˶ˆᗜˆ˵ )",
    "hello ♡",
    "hi ⋆★☆",
    "heyhey ⋆｡°✩",
]


EVENING = [
    "good evening stardust",
    "night mode activated",
    "watch ur screentime dude!!!",
    "hello darkness my riceball",

    "good evening rigel",
    "evening, gentle star",
    "hi nightfriend",
    "soft hours begin",
    "time to unwind",
    "good evening ♡",
    "evening calm mode",
    "hi… slow down ok",
    "wrap up time",
    "lights low pls",
    "rest mode soon?",

    "nighttime mischief",
    "evening goblin mode",
    "hello tiny nocturnal being",
    "why are we still awake",
    "evening… again…",
    "its giving insomnia",
    "night mode: unhinged",
    "hello darkness (affectionate)",
    "hey bestie u ok",
    "evening vibes: feral",

    "take off ur lil shoes",
    "pls rest ur eyes",
    "stretch before bed",
    "drink water 1 last time",
    "wash ur face pls",
    "did u eat dinner??",
    "close tabs. breathe.",
    "sleep soon? pls?",
    "put phone down i dare u",
    "go be cozy rn",

    "the stars are on",
    "evening starshine",
    "nightfall: gentle",
    "hello quiet universe",
    "the sky is velvet",
    "moon says hi",
    "stardust hours",
    "the night is soft",
    "cosmos says: rest",
    "evening glow mode",

    "evening ₍ᐢ. .ᐢ₎",
    "good evening (ᗜˬᗜ)",
    "night night ( ˶ˆᗜˆ˵ )",
    "evening ♡",
    "hi ⋆★☆",
    "nighttime ⋆｡°✩",
]

