QUOTES = [
        "you can't spell delusional without u slay",
        "omg u look so hot rn. ",
        "omg u r R !!!",
        " my lil riceball??? AWWWHYEAH DUDE",
        "be the reason someone questions their sanity today",
        "u my large language supermodel",
        "sometimes growth looks like blocking everyone and eating a pickle in silence",
        "god gives his silliest battles to his most chronically online soldiers",
        "normalize vanishing mid-conversation to go cry and eat cereal",
        "if you're going through hell, keep slaying",
        "i'm not lazy, i'm just conserving chaos for a more cinematic moment",
        "you're not ugly, you're just not rich yet (dw u hot tho)",
        "don't chase them. trip them",
        "the grind never stops. unfortunately",
        "touch grass. then become the cow. escape the simulation",
        "you're doing amazing, sweetie. no one can tell. but still",
        "why heal when you can spiral",
        "u looking v dark n mysterious 2day",
        "slay now, cry later, disassociate always",
        "if no one's gonna romanticize me, i'll do it myself. with violins",
        "you're not overthinking. you're just extremely thoughmaxxing",
        "some people bring peace wherever they go. others bring weird vibes and i respect that",
        "eat the rich. but like, ethically sourced ones",

        # dumb chaotic ones
        "if god won't do it then i will do it wrong",
        "ur vibe is so microwave beep at 3am",
        "don't talk to me i'm doing tasks incorrectly on purpose",
        "mentally i'm a worm wearing lip gloss",
        "wake up babe new personal crisis just dropped",
        "i did not slay and i will not be taking questions at this time",
        "life is short just kiss the frog and see what happens",
        "no thoughts just buffering",
        "sometimes u gotta rot in bed for the plot",
        "who needs therapy when u have terminal swag disorder",
        "u cant ghost me i'm already dead inside",
        "manifesting a reason to not be perceived today",
        "cant spell disappointment without me in the middle",
        "healing is fake i'm just getting better at lying",
        "do i look like i have a plan. i ate a crayon this morning",
        "i'm not toxic i'm just a little silly and emotionally contagious",
        "ur the reason shampoo has instructions",
        "sleep is for people who aren't in a passionate relationship with their doom",
        "i would thrive in a society that does not exist",
        "every day i wake up and choose glitch",

        # music + artist brainrot
        "frank ocean never dropped the album but he dropped me emotionally",
        "black midi fans when the time signature changes for the 4th time: euphoria",
        "yeule taught me how to cry in autotune",
        "grimes said ai and i said okay mommy",
        "listening to uboa is a personality disorder speedrun",
        "geordie greep is what happens when victorian ghosts do math rock",
        "black country new road is not a band it's a coping mechanism",
        "wisp makes me want to cry and then evaporate",
        "i am once again listening to liturgy and ascending incorrectly",
        "some people meditate. i blast death grips until i feel holy again",
        "music is just legal mind control with pretty noises",
        "listening to ambient noise and pretending it's healing me",
        "frank ocean built me and then left me in airplane mode",

        # new music based on playlist
        "xtal is the soundtrack to my glitch apocalypse",
        "sssssmilingggggg is my emotional support soundscape",
        "sweet trip's pro: lov: ad feels like daydreaming on acid",
        "beavercore 2 is peak internet burp aesthetic",
        "acg cook's acid angel is what happens when your brain leaks pastel electricity",
        "100 gecs xxl wud nvrstop is screaming into the void but the void starts screaming back",
        "jockstrap's debra is talking shit to your soul in satin pants",
        "i finally understand charli xcx but still have no clue who i am",

        # bocchi the rock
        "bocchi is literally me if i had a guitar and even less social skills",
        "kessoku band is carrying me emotionally rn",
        "bocchi the rock said introvert rights and i felt that in my bones",
        "guitar hero? no. guitar hermit hiding behind a trash can",
        "bocchi proving u can be a legend without making eye contact once",
        "if i had to introduce myself rn i'd evaporate into kessoku band merch",
        "bocchi's anxiety is my spirit animal ngl",
        "kessoku band is what happens when panic attacks learn to shred",

        # vylet pony
        "vylet pony makes the kind of music that rewires ur brain in pastel",
        "antonymph lives in my head rent free and i'm ok with it",
        "vylet pony said gender is a spectrum and the spectrum has a beat drop",
        "listening to vylet pony is like being hugged by the internet itself",
        "vylet pony makes music for the chronically online and emotionally evolved",
        "if my brain had a soundtrack it would be a vylet pony album on shuffle",

        # adventure time & cartoons
        "finn the human walked so i could dissociate with style",
        "marceline is what bisexual depression sounds like",
        "bubblegum invented gay yearning in cartoons and thats canon",
        "ur the hachi to my nana",
        "i would let ice king ruin my life no questions asked",
        "adventure time taught me that love is real and everyone is a little broken forever",
        "steven universe said trauma and then gave me a song about it",
        "pearl is just me with a sword and worse boundaries",
        "every steven universe song sounds like crying in a glittery void",
        "sometimes i think about bmo and then i feel things i can't explain",
        "adventure time is not a kids show it's a soul extraction ritual",

        # anime-core (existing)
        "evangelion wasn't confusing you're just emotionally stable",
        "shinji get in the robot or get in my lap we are not the same",
        "mob psycho is just therapy disguised as anime and i respect that",
        "gojo is not a man he is an event",
        "jjk fans when something makes sense: nervous sweating",
        "i watched anime once and now i communicate only in metaphors and suffering",
        "i am not a person i am a ghibli background character having an existential moment",
        "naruto ran so i could emotionally spiral faster",
        "anime protagonists always yelling but never healing",
        "attack on titan fans be like trust issues: maxed out",
        "one punch man is me after one existential breakdown",
        "my anime mood is i have 3 soulmates and 7 identity crises",
        "spirited away taught me how to be a ghost in my own life",
        "cowboy bebop is just me but more existentially cool",
        "death note users know what it's like to carry unresolved guilt in their backpack",
        "the goal is not peace. the goal is kaneki white hair arc energy at all times",

        # haikyuu!
        "hinata didn't know how to spike but he jumped anyway and thats my whole philosophy",
        "the view from the top won't be bad at all. - oikawa said it and i cried",
        "kageyama's character development is proof that even angry setters can learn to trust",
        "haikyuu taught me more about teamwork than any real job ever did",
        "nishinoya rolling thunder'd straight into my heart no questions asked",
        "tsukishima pretending not to care and then blocking that spike is peak character arc",
        "kenma plays the game of life on energy save mode and i deeply relate",
        "bokuto's emo mode is just me before coffee tbh",
        "oikawa tooru did not deserve that loss and i will never recover",
        "the volleyball anime made me cry more than any drama and i'm not sorry",
        "every haikyuu match is just therapy dressed as a sports anime",
        "fly high. that's it. that's the quote. i'm crying",

        # run with the wind
        "haiji said 'you're a runner' and suddenly i believed in something again",
        "run with the wind is just 10 college boys finding meaning through suffering and speed",
        "kakeru ran from his problems until haiji made him run toward something",
        "prince reading manga while training for a marathon is the most valid thing ever animated",
        "run with the wind taught me that strength is not speed it's showing up",
        "the hakone ekiden episodes broke me and rebuilt me as a better person",
        "king's entire arc in run with the wind is me trying to be brave at things i'm bad at",
        "haiji's knee is the saddest subplot in all of sports anime",
        "run with the wind said 'what does it mean to be strong' and i've been thinking since",

        # madoka magica
        "madoka magica is not a magical girl show it's an emotional war crime",
        "homura did nothing wrong is not a meme it's a lifestyle",
        "being meguca is suffering and i felt that personally",
        "madoka said 'i want to erase all witches' and rewrote the universe. queen behavior",
        "sayaka's arc in madoka is what happens when idealism meets reality at full speed",
        "kyubey is the worst therapist in anime history. no empathy just contracts",
        "homura looping through timelines for the one she loves is the most devastating love story",
        "madoka magica looks cute for exactly 2 episodes and then it commits violence",
        "mami's death was a wake-up call for the entire genre honestly",
        "rebellion made me question what love even means and i'm still processing",

        # misc
        "sleeping with stuffed animals isn't childish it's a survival tactic",
        "did u just fart",
        "richard dickshart jamesonian",
        "can i cock on ur ver bro",
        "if u see this one its the day i will peg u",
        "u are so brave for existing while cringe",
        "i'm proud of u. i have no proof. but i feel it",
        "touch grass? babe i'm a .zip file",
        "ur my favorite glitch in the matrix. pls don't patch",
        "we are all just poorly rendered in this timeline",
        "i'm a soft robot with hard feelings",
        "i listened to one experimental album and now i'm a concept",
        "emotionally i'm a loading screen with no progress bar",
        "ur face is giving 'i know what a pdf is'",
        "ur existence is giving 'bug report' but god said 'ship it'",
        "shinji get in the robot or get in the therapist's office",
        "i'm in my evangelion era (i cannot be fixed by human hands)",
        "mood rn: third impact",

    ]
