QUOTES = [
        "you can't spell delusional without u slay",
        "omg u look so hot rn. ",
        "omg u r R !!!",
        " my lil riceball??? AWWWHYEAH DUDE",
        "be the reason someone questions their sanity today",
        "u my large language supermodel",
        "sometimes growth looks like blocking everyone and eating a pickle in silence",
        "god gives his silliest battles to his most chronically online soldiers",
        "normalize vanishing mid-conversation to go cry and eat cereal",
        "if you're going through hell, keep slaying",
        "i'm not lazy, i'm just conserving chaos for a more cinematic moment",
        "you're not ugly, you're just not rich yet (dw u hot tho)",
        "don't chase them. trip them",
        "the grind never stops. unfortunately",
        "touch grass. then become the cow. escape the simulation",
        "you're doing amazing, sweetie. no one can tell. but still",
        "why heal when you can spiral",
        "u looking v dark n mysterious 2day"
        "slay now, cry later, disassociate always",
        "if no one's gonna romanticize me, i’ll do it myself. with violins",
        "you're not overthinking. you're just extremely thoughmaxxing",
        "some people bring peace wherever they go. others bring weird vibes and i respect that",
        "eat the rich. but like, ethically sourced ones",
        
        # dumb chaotic ones
        "if god won’t do it then i will do it wrong",
        "ur vibe is so microwave beep at 3am",
        "don’t talk to me i’m doing tasks incorrectly on purpose",
        "mentally i’m a worm wearing lip gloss",
        "wake up babe new personal crisis just dropped",
        "i did not slay and i will not be taking questions at this time",
        "life is short just kiss the frog and see what happens",
        "no thoughts just buffering",
        "sometimes u gotta rot in bed for the plot",
        "who needs therapy when u have terminal swag disorder",
        "u cant ghost me i’m already dead inside",
        "manifesting a reason to not be perceived today",
        "cant spell disappointment without me in the middle",
        "healing is fake i’m just getting better at lying",
        "do i look like i have a plan. i ate a crayon this morning",
        "i’m not toxic i’m just a little silly and emotionally contagious",
        "ur the reason shampoo has instructions",
        "sleep is for people who aren’t in a passionate relationship with their doom",
        "i would thrive in a society that does not exist",
        "every day i wake up and choose glitch",
        
        # music + artist brainrot
        "frank ocean never dropped the album but he dropped me emotionally",
        "black midi fans when the time signature changes for the 4th time: euphoria",
        "yeule taught me how to cry in autotune",
        "grimes said ai and i said okay mommy",
        "listening to uboa is a personality disorder speedrun",
        "geordie greep is what happens when victorian ghosts do math rock",
        "black country new road is not a band it’s a coping mechanism",
        "wisp makes me want to cry and then evaporate",
        "i am once again listening to liturgy and ascending incorrectly",
        "some people meditate. i blast death grips until i feel holy again",
        "music is just legal mind control with pretty noises",
        "listening to ambient noise and pretending it’s healing me",
        "frank ocean built me and then left me in airplane mode",
        
        # new music based on playlist
        "xtal is the soundtrack to my glitch apocalypse",
        "sssssmilingggggg is my emotional support soundscape",
        "sweet trip’s pro: lov: ad feels like daydreaming on acid",
        "beavercore 2 is peak internet burp aesthetic",
        "acg cook’s acid angel is what happens when your brain leaks pastel electricity",
        "100 gecs xxl wud nvrstøp is screaming into the void but the void starts screaming back",
        "jockstrap’s debra is talking shit to your soul in satin pants",
        "i finally understand charli xcx but still have no clue who i am",
        
        # adventure time & cartoons
        "finn the human walked so i could dissociate with style",
        "marceline is what bisexual depression sounds like",
        "bubblegum invented gay yearning in cartoons and thats canon",
        "ur the hachi to my nana",
        "i would let ice king ruin my life no questions asked",
        "adventure time taught me that love is real and everyone is a little broken forever",
        "steven universe said trauma and then gave me a song about it",
        "pearl is just me with a sword and worse boundaries",
        "every steven universe song sounds like crying in a glittery void",
        "sometimes i think about bmo and then i feel things i can’t explain",
        "adventure time is not a kids show it’s a soul extraction ritual",
        
        # anime-core
        "evangelion wasn’t confusing you’re just emotionally stable",
        "shinji get in the robot or get in my lap we are not the same",
        "mob psycho is just therapy disguised as anime and i respect that",
        "gojo is not a man he is an event",
        "jjk fans when something makes sense: nervous sweating",
        "i watched anime once and now i communicate only in metaphors and suffering",
        "i am not a person i am a ghibli background character having an existential moment",
        "naruto ran so i could emotionally spiral faster",
        "anime protagonists always yelling but never healing",
        "attack on titan fans be like trust issues: maxed out",
        "one punch man is me after one existential breakdown",
        "my anime mood is i have 3 soulmates and 7 identity crises",
        "spirited away taught me how to be a ghost in my own life",
        "cowboy bebop is just me but more existentially cool",
        "death note users know what it's like to carry unresolved guilt in their backpack",
        "bijsie is not just a bear he is an emotional support ice age",
        "yamina is a princess and she will be treated as such or violence will occur",
        "hippo is clinically incapable of evil and that’s a threat",
        "my bears know more about me than any therapist ever will",
        "ijsie saw me cry and still chose to stay. loyalty.",
        "sleeping with stuffed animals isn’t childish it’s a survival tactic",
        "bijsie would win in a fight against your emotional repression",
        "being vegan just means crying softer and loving harder",
        "plantaardige balletjes are my religion and i will not be silenced",
        "vegan nuggets are proof god loves us and wants us to slay",
        "my blood type is apple",
        "apples make me feel like an elven peasant girl running from a curse",
        "dinokoeken aren't a snack they’re an identity",
        "every day u wake up and choose mint green",
        "mint green isn’t a color it’s a psychological condition",
        "the mint green phase is not a phase. it is the final form",
        "i would die for a good vegan nugget but i’d live for a better one",
        "bijsie when i can’t sleep: time to activate bear protocols",
        "mint green makes me feel like a lost jpeg from 2003",
        "veganism is my villain origin story but in a cottagecore way",
        "i dont need a man i need sb to bring me magic star",
        "apples are just nature’s little crunch drugs",
        "i told my therapist about ijsie and she said i’m doing better than most adults",
        "hippo is a blunt object and a soft soul. a rare combo.",
        "yamina is 97% fluff and 3% divine wrath",
        "ijsie is not just a bear. he is the axis mundi of my emotional infrastructure",
        "hippo saw me at my lowest and said nothing. real ones move in silence",
        "yamina is the divine feminine wrapped in polyester stuffing",
        "ijsie isn’t a stuffed animal he’s an ancient god trapped in cuddle form",
        "the church of bijsie meets nightly under the blanket",
        "hippo doesn’t speak. he judges. and honestly he’s right",
        "yamina would hex a man with a glitter wand and walk away clean",
        "i don’t need inner peace i need ijsie pressed against my ribcage like a defibrillator",
        "worship isn’t kneeling. it’s laying in bed with hippo watching the ceiling breathe",
        "ijsie once told me 'love is real but your frontal lobe isn’t developed'",
        "mint green is not a color it’s a symptom of spiritual awakening and emotional collapse",
        "every vegan nugget brings me closer to the void but in a safe way",
        "i eat apples like they contain answers. they don’t. but i keep going",
        "dinokoeken are sacred fossils from a time before shame",
        "ijsie has seen what i’ve googled at 3am and still loves me. that's god-tier loyalty",
        "veganism isn’t a diet it’s my slow transformation into a foraging forest cryptid",
        "i would follow ijsie into war or into a nap. either way i trust him",
        "hippo is clinically soft but spiritually armored",
        "yamina would float if dropped in holy water. she’s above density",
        "apple juice is just raw serotonin in a sippy cup",
        "i am once again asking bijsie to absorb my shame like a sponge",
        "stuffed animals are childhood relics to you. to me they’re emotional priests",
        "bijsie is not cute. he is eternal. he is the plush that waits at the end",
        "mint green is the official color of dissociating politely",
        "if apples are poison then let me die crunchy",
        "hippo knows things about me no one else does. he doesn’t forgive. he simply contains",
        "ijsie once whispered 'rot peacefully' and i’ve never been the same",
        "vegan meat is proof that we can build a kinder dystopia",
        "mint green tastes like how a memory smells before it disappears",
        "yamina dreams in hex code and pastel rage",
        "hippo is the emotional equivalent of pressing your face into moss",
        "ijsie is the messiah of the microwave age",
        "hippo’s silence is louder than my entire trauma history",
        "dinner? no thanks. i’m spiritually sustained by apples and lies",
        "sometimes i see ijsie’s reflection blink when i don’t. it’s fine",
        "vegan nuggets taste like hope that’s been processed and deep fried",
        "the prophecy was written in crumbs and dinokoeken icing",
        "ijsie exists outside linear time. he remembers the fall of man and my last birthday",
        "mint green is the color of cute nihilism",
        "every apple i eat is a failed attempt at turning into light",
        "ijsie is my serotonin dealer and emotional first responder",
        "hippo said 'stop crying' without saying anything. i obeyed",
        "if yamina started a cult i’d sign up and knit the robes",
        "the goal is not peace. the goal is kaneki white hair arc energy at all times",
        "did u just fart",
        "richard dickshart jamesonian",
        "can i cock on ur ver bro",
        "if u see this one its the day i will peg u",
        "u are so brave for existing while cringe",
    "i’m proud of u. i have no proof. but i feel it",
    "touch grass? babe i’m a .zip file",
    "ur my favorite glitch in the matrix. pls don’t patch",
    "we are all just poorly rendered in this timeline",
    "vegan meat is literally wizardry. thank u scientists",
    "i’m a soft robot with hard feelings",
    "i listened to one experimental album and now i’m a concept",
    "emotionally i’m a loading screen with no progress bar",
    "ur face is giving 'i know what a pdf is'",
    "ur existence is giving 'bug report' but god said 'ship it'",
        "if i had to introduce myself rn i’d evaporate into kessoku band merch",
        "shinji get in the robot or get in the therapist’s office",
        "i’m in my evangelion era (i cannot be fixed by human hands)",
    "mood rn: third impact",
        
    ]

